# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180120_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Viewer', max_length=16),
        ),
    ]
