# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0008_auto_20180128_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_post_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_post_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='last_post_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
