# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20180203_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
            ],
        ),
    ]
