# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_posticon'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='post_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.PostIcon'),
        ),
    ]
