# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_privatemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='subject',
            field=models.CharField(max_length=80),
        ),
    ]
